export const data = [
  {
    img: "https://c.media-amazon.com/images/I/71y0jPPHNzL._AC_UL320_.jpg",
    title: "Crewneck Cotton Sweatshirt",
    rating: 4.6,
    reviews: "(324 reviews)",
    prevPrice: "$40.00",
    newPrice: "$29.99",
    style: "Comfort",
    color: "gray",
    category: "sweatshirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/61kRx2g7EsL._AC_UL320_.jpg",
    title: "Fleece Pullover Hoodie",
    rating: 4.6,
    reviews: "(754 reviews)",
    prevPrice: "$40.00",
    newPrice: "$32.99",
    style: "Athletic",
    color: "black",
    category: "hoodies",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71oF5-0Kl8L._AC_UL320_.jpg",
    title: "Stretch Fit Jeans",
    rating: 4.2,
    reviews: "(30,000 reviews)",
    prevPrice: "$35.00",
    newPrice: "$26.60",
    style: "Comfort",
    color: "denim",
    category: "jeans",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71FZ2H3hooL._AC_UL320_.jpg",
    title: "2-in-1 Workout Shorts",
    rating: 4.4,
    reviews: "(11 reviews)",
    prevPrice: "$35.00",
    newPrice: "$26.99",
    style: "Athletic",
    color: "black",
    category: "shorts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71RPinQjeCL._AC_UL320_.jpg",
    title: "Loose Fit Tee",
    rating: 4.6,
    reviews: "(153,100 reviews)",
    prevPrice: "$30.00",
    newPrice: "$19.99",
    style: "Comfort",
    color: "white",
    category: "t-shirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/619tikhRvbL._AC_UL320_.jpg",
    title: "Linen Beach Set",
    rating: 4.3,
    reviews: "(3,000 reviews)",
    prevPrice: "$60.00",
    newPrice: "$44.99",
    style: "Other",
    color: "white",
    category: "sets",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/81D+bCgn8hL._AC_UL320_.jpg",
    title: "EcoSmart Fleece",
    rating: 4.6,
    reviews: "(153,500 reviews)",
    prevPrice: "$18.00",
    newPrice: "$9.50",
    style: "Comfort",
    color: "navy",
    category: "sweatshirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71UIENuQxXL._AC_UL320_.jpg",
    title: "Quick-Dry Polo Pack",
    rating: 4.4,
    reviews: "(4,100 reviews)",
    prevPrice: "$55.00",
    newPrice: "$43.99",
    style: "Athletic",
    color: "multi",
    category: "shirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71zEMu-ZwoL._AC_UL320_.jpg",
    title: "Waffle Tracksuit Set",
    rating: 4.0,
    reviews: "(19 reviews)",
    prevPrice: "$35.00",
    newPrice: "$25.99",
    style: "Other",
    color: "gray",
    category: "sets",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/61BqqBbrwpL._AC_UL320_.jpg",
    title: "Running Tee UPF50+",
    rating: 4.7,
    reviews: "(27 reviews)",
    prevPrice: "$12.99",
    newPrice: "$10.99",
    style: "Athletic",
    color: "white",
    category: "t-shirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/81HsZOdpbJL._AC_UL320_.jpg",
    title: "Henley Tee Classic",
    rating: 4.4,
    reviews: "(10,300 reviews)",
    prevPrice: "$30.99",
    newPrice: "$19.78",
    style: "Comfort",
    color: "black",
    category: "t-shirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/813X3sta1sL._AC_UL320_.jpg",
    title: "Solid Knit Hoodie",
    rating: 4.6,
    reviews: "(5,200 reviews)",
    prevPrice: "$34.99",
    newPrice: "$30.79",
    style: "Comfort",
    color: "gray",
    category: "hoodies",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/71O7gCAToYL._AC_UL320_.jpg",
    title: "Short Sleeve Beach Shirt",
    rating: 4.5,
    reviews: "(40 reviews)",
    prevPrice: "$35.00",
    newPrice: "$24.99",
    style: "Other",
    color: "white",
    category: "shirts",
    gender: "men"
  },
  {
    img: "https://c.media-amazon.com/images/I/51F7S8AVafL._AC_UL320_.jpg",
    title: "V-Neck Linen Blouse",
    rating: 1.7,
    reviews: "(40 reviews)",
    prevPrice: "$30.00",
    newPrice: "$22.99",
    style: "Casual",
    color: "white",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/61WfO5R3KSL._AC_UL320_.jpg",
    title: "Boho Floral Linen Blouse",
    rating: 2.2,
    reviews: "(35 reviews)",
    prevPrice: "$35.00",
    newPrice: "$28.99",
    style: "Boho",
    color: "floral",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/51qc1w84MhL._AC_UL320_.jpg",
    title: "Floral Crewneck Shirt",
    rating: 4.2,
    reviews: "(20 reviews)",
    prevPrice: "$30.00",
    newPrice: "$25.98",
    style: "Casual",
    color: "multi",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/61CcTPBfpiL._AC_UL320_.jpg",
    title: "Short Sleeve Tunic",
    rating: 3.4,
    reviews: "(9 reviews)",
    prevPrice: "$30.00",
    newPrice: "$25.99",
    style: "Relaxed",
    color: "solid",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/51HPYzIklzL._AC_UL320_.jpg",
    title: "Wide-Leg Lounge Set",
    rating: 4.5,
    reviews: "(28 reviews)",
    prevPrice: "$35.00",
    newPrice: "$29.99",
    style: "Lounge",
    color: "neutral",
    category: "sets",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/61qJlwGq8UL._AC_UL320_.jpg",
    title: "Mock Neck Travel Set",
    rating: 4.3,
    reviews: "(2,600 reviews)",
    prevPrice: "$45.00",
    newPrice: "$34.99",
    style: "Lounge",
    color: "gray",
    category: "sets",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/713HlhuVeKL._AC_UL320_.jpg",
    title: "Button T-Shirt Tee",
    rating: 4.3,
    reviews: "(52 reviews)",
    prevPrice: "$24.00",
    newPrice: "$18.99",
    style: "Cute",
    color: "pastel",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/71f-yxtdjqL._AC_UL320_.jpg",
    title: "Knit Tank Vest",
    rating: 4.4,
    reviews: "(238 reviews)",
    prevPrice: "$29.98",
    newPrice: "$19.98",
    style: "Trendy",
    color: "cream",
    category: "tops",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/51gDfvc+eJL._AC_UL320_.jpg",
    title: "Jogger Lounge Pants",
    rating: 4.3,
    reviews: "(25,200 reviews)",
    prevPrice: "$34.99",
    newPrice: "$28.49",
    style: "Athletic",
    color: "black",
    category: "pants",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/51pgj61zt2L._AC_UL320_.jpg",
    title: "Half-Zip Sweatsuit",
    rating: 4.2,
    reviews: "(2,400 reviews)",
    prevPrice: "$55.00",
    newPrice: "$47.99",
    style: "Lounge",
    color: "neutral",
    category: "sets",
    gender: "women"
  },
  {
    img: "https://c.media-amazon.com/images/I/91OlSrOsY7L._AC_UL320_.jpg",
    title: "Plaid Boxer Shorts",
    rating: 4.4,
    reviews: "(285 reviews)",
    prevPrice: "$14.99",
    newPrice: "$8.99",
    style: "Sleepwear",
    color: "plaid",
    category: "shorts",
    gender: "women"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61gQVDClZRL._AC_SX569_.jpg",
    "title": "Men's Slim Fit Casual Shirt",
    "rating": 4,
    "reviews": "(320 reviews)",
    "prevPrice": "$45.00",
    "newPrice": "$30.00",
    "style": "Comfort",
    "color": "blue",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SCZN1ez0BA9NkF",
    "price": "price_1RIAF3CkS2P2sDdJ9fjqkCAM"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71cLAqOr0tL._AC_SX679_.jpg",
    "title": "Women's High Waist Skinny Jeans",
    "rating": 3,
    "reviews": "(210 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$40.00",
    "style": "Athletic",
    "color": "black",
    "category": "jeans",
    "gender": "women",
    "id": "prod_SCZNvaLkvZBEN7",
    "price": "price_1RIAF3CkS2P2sDdJ4MkLkDgb"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71wp-f9m0-L._AC_SY741_.jpg",
    "title": "Unisex Hoodie",
    "rating": 2,
    "reviews": "(500 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$200.00",
    "style": "Professional",
    "color": "gray",
    "category": "hoodies",
    "gender": "unisex",
    "id": "prod_SCZNt8FrQO4otH",
    "price": "price_1RIAF4CkS2P2sDdJdrFmhhDN"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71BHSXSzqeL._AC_SY741_.jpg",
    "title": "Men's Classic Chinos",
    "rating": 5,
    "reviews": "(190 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$37.00",
    "style": "Other",
    "color": "khaki",
    "category": "pants",
    "gender": "men",
    "id": "prod_SCZNyvppN9rNhn",
    "price": "price_1RIAF4CkS2P2sDdJDlzn1jjs"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71QXvsxofpL._AC_UL320_.jpg",
    "title": "Women's Summer Dress",
    "rating": 5,
    "reviews": "(275 reviews)",
    "prevPrice": "$70.00",
    "newPrice": "$50.00",
    "style": "Comfort",
    "color": "red",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SCZNDjRoPsSHUf",
    "price": "price_1RIAF5CkS2P2sDdJRnHbtYBb"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81Y6r7df7OL._AC_SX569_.jpg",
    "title": "Men's Business Casual Shirt",
    "rating": 5,
    "reviews": "(275 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$42.00",
    "style": "Professional",
    "color": "white",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SCZNfH1q9twRqg",
    "price": "price_1RIAF6CkS2P2sDdJTxA8d5xW"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71htqyXvfSL._AC_SX679_.jpg",
    "title": "Men's Stretch Jeans",
    "rating": 5,
    "reviews": "(315 reviews)",
    "prevPrice": "$80.00",
    "newPrice": "$55.00",
    "style": "Comfort",
    "color": "blue",
    "category": "jeans",
    "gender": "men",
    "id": "prod_SCZNrTX7zge6XS",
    "price": "price_1RIAF6CkS2P2sDdJ8GrB5qF3"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71rmcjnJiqL._AC_SX569_.jpg",
    "title": "Casual Hoodie for Women",
    "rating": 5,
    "reviews": "(430 reviews)",
    "prevPrice": "$65.00",
    "newPrice": "$45.00",
    "style": "Athletic",
    "color": "black",
    "category": "hoodies",
    "gender": "women",
    "id": "prod_SCZNq00qlxRtDs",
    "price": "price_1RIAF7CkS2P2sDdJekpRQqF5"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61gamoidnBL._AC_SY741_.jpg",
    "title": "Relaxed Fit Cargo Pants",
    "rating": 5,
    "reviews": "(200 reviews)",
    "prevPrice": "$75.00",
    "newPrice": "$50.00",
    "style": "Other",
    "color": "gray",
    "category": "pants",
    "gender": "unisex",
    "id": "prod_SCZNjnFMJMa4qK",
    "price": "price_1RIAF7CkS2P2sDdJGeFMsvYR"
  },
  {
    "img": "https://m.media-amazon.com/images/I/51gpWxyUseL._AC_SX679_.jpg",
    "title": "Women's Evening Gown",
    "rating": 5,
    "reviews": "(300 reviews)",
    "prevPrice": "$120.00",
    "newPrice": "$90.00",
    "style": "Professional",
    "color": "navy",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SCZNFWWtsj3XmE",
    "price": "price_1RIAF8CkS2P2sDdJEs6iuNp8"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71n4aYYXM-L._AC_SY741_.jpg",
    "title": "Men's Office Pants",
    "rating": 5,
    "reviews": "(270 reviews)",
    "prevPrice": "$90.00",
    "newPrice": "$65.00",
    "style": "Professional",
    "color": "black",
    "category": "pants",
    "gender": "men",
    "id": "prod_SCZNG77qIjKvFw",
    "price": "price_1RIAF8CkS2P2sDdJCim8Fb25"
  },
  {
    "img": "https://m.media-amazon.com/images/I/611DCpUuhfL._AC_SL1500_.jpg",
    "title": "Comfy Lounge Hoodie",
    "rating": 5,
    "reviews": "(510 reviews)",
    "prevPrice": "$85.00",
    "newPrice": "$60.00",
    "style": "Comfort",
    "color": "gray",
    "category": "hoodies",
    "gender": "unisex",
    "id": "prod_SCZNS5uCc5qNAP",
    "price": "price_1RIAF9CkS2P2sDdJ0yq06rbj"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61oW09i5MAL._AC_SX679_.jpg",
    "title": "Casual Summer Dress",
    "rating": 5,
    "reviews": "(340 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$40.00",
    "style": "Other",
    "color": "yellow",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SCZNOtW6XNMnE9",
    "price": "price_1RIAF9CkS2P2sDdJZXdjdi4e"
  },
  {
    "img": "https://m.media-amazon.com/images/I/91tc0Gl1eBL._AC_SX679_.jpg",
    "title": "Men's Flannel Shirt",
    "rating": 5,
    "reviews": "(370 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$45.00",
    "style": "Comfort",
    "color": "red",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SCZNDaGwwn8kUk",
    "price": "price_1RIAFACkS2P2sDdJW5XOMPaJ"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71+riO7d0NL._AC_SX679_.jpg",
    "title": "Skinny Fit Jeans",
    "rating": 5,
    "reviews": "(490 reviews)",
    "prevPrice": "$95.00",
    "newPrice": "$70.00",
    "style": "Athletic",
    "color": "black",
    "category": "jeans",
    "gender": "women",
    "id": "prod_SCZNSHiQn4NDzj",
    "price": "price_1RIAFBCkS2P2sDdJ47Z4tfZ2"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81kAhEYvQwL._AC_UL320_.jpg",
    "title": "Men's Athletic Polo Shirt",
    "rating": 4.5,
    "reviews": "(250 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$35.00",
    "style": "Athletic",
    "color": "green",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SCZNjKWXqW1G2N",
    "price": "price_1RIAFBCkS2P2sDdJ6DCRxteP"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81QDD1ULPzL._AC_UL320_.jpg",
    "title": "Women's Maxi Skirt",
    "rating": 4,
    "reviews": "(180 reviews)",
    "prevPrice": "$65.00",
    "newPrice": "$48.00",
    "style": "Comfort",
    "color": "floral",
    "category": "skirts",
    "gender": "women",
    "id": "prod_SCZNB3uYbNsYt5",
    "price": "price_1RIAFCCkS2P2sDdJNvcIxnUi"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81p-B7OS7VL._AC_UL320_.jpg",
    "title": "Unisex Denim Jacket",
    "rating": 4.8,
    "reviews": "(400 reviews)",
    "prevPrice": "$90.00",
    "newPrice": "$70.00",
    "style": "Other",
    "color": "blue",
    "category": "jackets",
    "gender": "unisex",
    "id": "prod_SCZN7n2YTloJna",
    "price": "price_1RIAFCCkS2P2sDdJWNy4ZLTX"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71MpFHOznXL._AC_UL320_.jpg",
    "title": "Men's Slim Fit Blazer",
    "rating": 4.7,
    "reviews": "(220 reviews)",
    "prevPrice": "$120.00",
    "newPrice": "$95.00",
    "style": "Professional",
    "color": "navy",
    "category": "blazers",
    "gender": "men",
    "id": "prod_SCZNPZPRI4rx6N",
    "price": "price_1RIAFDCkS2P2sDdJkcm0Ts5s"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61IqZD8hYDL._AC_UL320_.jpg",
    "title": "Women's Athletic Leggings",
    "rating": 4.6,
    "reviews": "(350 reviews)",
    "prevPrice": "$45.00",
    "newPrice": "$32.00",
    "style": "Athletic",
    "color": "black",
    "category": "leggings",
    "gender": "women",
    "id": "prod_SCZNLhkUHBTMD6",
    "price": "price_1RIAFDCkS2P2sDdJGpj49hbq"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71IbGJbFcnL._AC_UL320_.jpg",
    "title": "Men's Crew Neck Sweater",
    "rating": 4.4,
    "reviews": "(290 reviews)",
    "prevPrice": "$70.00",
    "newPrice": "$50.00",
    "style": "Comfort",
    "color": "charcoal",
    "category": "sweaters",
    "gender": "men",
    "id": "prod_SCZOKa4Qe6GkFU",
    "price": "price_1RIAFECkS2P2sDdJkUvJWrap"
  },
  {
    "img": "https://m.media-amazon.com/images/I/815VJpmh7PL._AC_UL320_.jpg",
    "title": "Women's Knit Cardigan",
    "rating": 4.3,
    "reviews": "(260 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$42.00",
    "style": "Other",
    "color": "beige",
    "category": "cardigans",
    "gender": "women",
    "id": "prod_SCZOMY1KuVWubx",
    "price": "price_1RIAFFCkS2P2sDdJa6D5i3kf"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71CFN6Cf9CL._AC_UL320_.jpg",
    "title": "Unisex Graphic T-Shirt",
    "rating": 4.2,
    "reviews": "(450 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$25.00",
    "style": "Comfort",
    "color": "white",
    "category": "t-shirts",
    "gender": "unisex",
    "id": "prod_SCZOTz0spvkyI3",
    "price": "price_1RIAFFCkS2P2sDdJSvpeMv7r"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71CxHBIhkiL._AC_UL320_.jpg",
    "title": "Men's Leather Jacket",
    "rating": 4.9,
    "reviews": "(310 reviews)",
    "prevPrice": "$150.00",
    "newPrice": "$120.00",
    "style": "Other",
    "color": "black",
    "category": "jackets",
    "gender": "men",
    "id": "prod_SCZO8TuNRqcw6N",
    "price": "price_1RIAFGCkS2P2sDdJf75aQr1E"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71c1emXTEXL._AC_UL320_.jpg",
    "title": "Women's Off-Shoulder Top",
    "rating": 4.1,
    "reviews": "(230 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$38.00",
    "style": "Athletic",
    "color": "pink",
    "category": "tops",
    "gender": "women",
    "id": "prod_SCZOTEtiwHxZI8",
    "price": "price_1RIAFGCkS2P2sDdJJOndLr1A"
  }
];

// TODO have newPrice set from stripe data and not stored here.
export default data;