export const data = [
  {
    "img": "https://c.media-amazon.com/images/I/71y0jPPHNzL._AC_UL320_.jpg",
    "title": "Crewneck Cotton Sweatshirt",
    "rating": 4.6,
    "reviews": "(324 reviews)",
    "prevPrice": "$40.00",
    "newPrice": "$29.99",
    "style": "Comfort",
    "color": "gray",
    "category": "sweatshirts",
    "gender": "men",
    "id": "prod_SFA7xnC3YyF0w6",
    "price": "price_1RKfnZCkS2P2sDdJQYYJSFGG"
  },
  {
    "img": "https://c.media-amazon.com/images/I/61kRx2g7EsL._AC_UL320_.jpg",
    "title": "Fleece Pullover Hoodie",
    "rating": 4.6,
    "reviews": "(754 reviews)",
    "prevPrice": "$40.00",
    "newPrice": "$32.99",
    "style": "Athletic",
    "color": "black",
    "category": "hoodies",
    "gender": "men",
    "id": "prod_SFA7bsfuYdbunh",
    "price": "price_1RKfnZCkS2P2sDdJhGcAr9PZ"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71oF5-0Kl8L._AC_UL320_.jpg",
    "title": "Stretch Fit Jeans",
    "rating": 4.2,
    "reviews": "(30,000 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$26.60",
    "style": "Comfort",
    "color": "denim",
    "category": "jeans",
    "gender": "men",
    "id": "prod_SFA7qzS6W2n0Sq",
    "price": "price_1RKfnaCkS2P2sDdJMP2xyniP"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71FZ2H3hooL._AC_UL320_.jpg",
    "title": "2-in-1 Workout Shorts",
    "rating": 4.4,
    "reviews": "(11 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$26.99",
    "style": "Athletic",
    "color": "black",
    "category": "shorts",
    "gender": "men",
    "id": "prod_SFA7lvsUDFx3Ss",
    "price": "price_1RKfnaCkS2P2sDdJPsqoiEc4"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71RPinQjeCL._AC_UL320_.jpg",
    "title": "Loose Fit Tee",
    "rating": 4.6,
    "reviews": "(153,100 reviews)",
    "prevPrice": "$30.00",
    "newPrice": "$19.99",
    "style": "Comfort",
    "color": "white",
    "category": "t-shirts",
    "gender": "men",
    "id": "prod_SFA7SdCIyT8Rvp",
    "price": "price_1RKfnbCkS2P2sDdJoaUMaKSS"
  },
  {
    "img": "https://c.media-amazon.com/images/I/619tikhRvbL._AC_UL320_.jpg",
    "title": "Linen Beach Set",
    "rating": 4.3,
    "reviews": "(3,000 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$44.99",
    "style": "Other",
    "color": "white",
    "category": "sets",
    "gender": "men",
    "id": "prod_SFA7GdOzcIDufs",
    "price": "price_1RKfnbCkS2P2sDdJRqDuHjUD"
  },
  {
    "img": "https://c.media-amazon.com/images/I/81D+bCgn8hL._AC_UL320_.jpg",
    "title": "EcoSmart Fleece",
    "rating": 4.6,
    "reviews": "(153,500 reviews)",
    "prevPrice": "$18.00",
    "newPrice": "$9.50",
    "style": "Comfort",
    "color": "navy",
    "category": "sweatshirts",
    "gender": "men",
    "id": "prod_SFA7zwrfTpssa2",
    "price": "price_1RKfncCkS2P2sDdJwhxFoCGF"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71UIENuQxXL._AC_UL320_.jpg",
    "title": "Quick-Dry Polo Pack",
    "rating": 4.4,
    "reviews": "(4,100 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$43.99",
    "style": "Athletic",
    "color": "multi",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA7XBOkugIB1x",
    "price": "price_1RKfndCkS2P2sDdJmvXyXvia"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71zEMu-ZwoL._AC_UL320_.jpg",
    "title": "Waffle Tracksuit Set",
    "rating": 4,
    "reviews": "(19 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$25.99",
    "style": "Other",
    "color": "gray",
    "category": "sets",
    "gender": "men",
    "id": "prod_SFA7kIy3u7sgCg",
    "price": "price_1RKfndCkS2P2sDdJ9etm9MkB"
  },
  {
    "img": "https://c.media-amazon.com/images/I/61BqqBbrwpL._AC_UL320_.jpg",
    "title": "Running Tee UPF50+",
    "rating": 4.7,
    "reviews": "(27 reviews)",
    "prevPrice": "$12.99",
    "newPrice": "$10.99",
    "style": "Athletic",
    "color": "white",
    "category": "t-shirts",
    "gender": "men",
    "id": "prod_SFA7hYzzCIIx4v",
    "price": "price_1RKfneCkS2P2sDdJVLWFP12u"
  },
  {
    "img": "https://c.media-amazon.com/images/I/81HsZOdpbJL._AC_UL320_.jpg",
    "title": "Henley Tee Classic",
    "rating": 4.4,
    "reviews": "(10,300 reviews)",
    "prevPrice": "$30.99",
    "newPrice": "$19.78",
    "style": "Comfort",
    "color": "black",
    "category": "t-shirts",
    "gender": "men",
    "id": "prod_SFA79SCe8GV2R6",
    "price": "price_1RKfneCkS2P2sDdJdGnxgQeQ"
  },
  {
    "img": "https://c.media-amazon.com/images/I/813X3sta1sL._AC_UL320_.jpg",
    "title": "Solid Knit Hoodie",
    "rating": 4.6,
    "reviews": "(5,200 reviews)",
    "prevPrice": "$34.99",
    "newPrice": "$30.79",
    "style": "Comfort",
    "color": "gray",
    "category": "hoodies",
    "gender": "men",
    "id": "prod_SFA7sWlGBvwRen",
    "price": "price_1RKfnfCkS2P2sDdJ0AgohTEm"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71O7gCAToYL._AC_UL320_.jpg",
    "title": "Short Sleeve Beach Shirt",
    "rating": 4.5,
    "reviews": "(40 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$24.99",
    "style": "Other",
    "color": "white",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA75qpmAjeclF",
    "price": "price_1RKfngCkS2P2sDdJd4b1uNBW"
  },
  {
    "img": "https://c.media-amazon.com/images/I/51F7S8AVafL._AC_UL320_.jpg",
    "title": "V-Neck Linen Blouse",
    "rating": 1.7,
    "reviews": "(40 reviews)",
    "prevPrice": "$30.00",
    "newPrice": "$22.99",
    "style": "Casual",
    "color": "white",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA7DmoPmPyKZq",
    "price": "price_1RKfngCkS2P2sDdJAhJxr9g9"
  },
  {
    "img": "https://c.media-amazon.com/images/I/61WfO5R3KSL._AC_UL320_.jpg",
    "title": "Boho Floral Linen Blouse",
    "rating": 2.2,
    "reviews": "(35 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$28.99",
    "style": "Boho",
    "color": "floral",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA7Ei5Ww0rTAy",
    "price": "price_1RKfnhCkS2P2sDdJGmxoxA1s"
  },
  {
    "img": "https://c.media-amazon.com/images/I/51qc1w84MhL._AC_UL320_.jpg",
    "title": "Floral Crewneck Shirt",
    "rating": 4.2,
    "reviews": "(20 reviews)",
    "prevPrice": "$30.00",
    "newPrice": "$25.98",
    "style": "Casual",
    "color": "multi",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA7f1ADrMUsGG",
    "price": "price_1RKfnhCkS2P2sDdJA0qo94sd"
  },
  {
    "img": "https://c.media-amazon.com/images/I/61CcTPBfpiL._AC_UL320_.jpg",
    "title": "Short Sleeve Tunic",
    "rating": 3.4,
    "reviews": "(9 reviews)",
    "prevPrice": "$30.00",
    "newPrice": "$25.99",
    "style": "Relaxed",
    "color": "solid",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA7DGKjooorLd",
    "price": "price_1RKfniCkS2P2sDdJuLbxSsIi"
  },
  {
    "img": "https://c.media-amazon.com/images/I/51HPYzIklzL._AC_UL320_.jpg",
    "title": "Wide-Leg Lounge Set",
    "rating": 4.5,
    "reviews": "(28 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$29.99",
    "style": "Lounge",
    "color": "neutral",
    "category": "sets",
    "gender": "women",
    "id": "prod_SFA7JplExpQNT2",
    "price": "price_1RKfniCkS2P2sDdJjbMuwf3P"
  },
  {
    "img": "https://c.media-amazon.com/images/I/61qJlwGq8UL._AC_UL320_.jpg",
    "title": "Mock Neck Travel Set",
    "rating": 4.3,
    "reviews": "(2,600 reviews)",
    "prevPrice": "$45.00",
    "newPrice": "$34.99",
    "style": "Lounge",
    "color": "gray",
    "category": "sets",
    "gender": "women",
    "id": "prod_SFA79sYijT7nPi",
    "price": "price_1RKfnjCkS2P2sDdJVRaCnqeY"
  },
  {
    "img": "https://c.media-amazon.com/images/I/713HlhuVeKL._AC_UL320_.jpg",
    "title": "Button T-Shirt Tee",
    "rating": 4.3,
    "reviews": "(52 reviews)",
    "prevPrice": "$24.00",
    "newPrice": "$18.99",
    "style": "Cute",
    "color": "pastel",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA8Wpvd4fVsw1",
    "price": "price_1RKfnkCkS2P2sDdJclnZv8CB"
  },
  {
    "img": "https://c.media-amazon.com/images/I/71f-yxtdjqL._AC_UL320_.jpg",
    "title": "Knit Tank Vest",
    "rating": 4.4,
    "reviews": "(238 reviews)",
    "prevPrice": "$29.98",
    "newPrice": "$19.98",
    "style": "Trendy",
    "color": "cream",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA8d0lgfJvORt",
    "price": "price_1RKfnkCkS2P2sDdJdofrjtoU"
  },
  {
    "img": "https://c.media-amazon.com/images/I/51gDfvc+eJL._AC_UL320_.jpg",
    "title": "Jogger Lounge Pants",
    "rating": 4.3,
    "reviews": "(25,200 reviews)",
    "prevPrice": "$34.99",
    "newPrice": "$28.49",
    "style": "Athletic",
    "color": "black",
    "category": "pants",
    "gender": "women",
    "id": "prod_SFA8eXRbz3F1CO",
    "price": "price_1RKfnlCkS2P2sDdJSGiNlX3B"
  },
  {
    "img": "https://c.media-amazon.com/images/I/51pgj61zt2L._AC_UL320_.jpg",
    "title": "Half-Zip Sweatsuit",
    "rating": 4.2,
    "reviews": "(2,400 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$47.99",
    "style": "Lounge",
    "color": "neutral",
    "category": "sets",
    "gender": "women",
    "id": "prod_SFA8NDJF5hvuXr",
    "price": "price_1RKfnlCkS2P2sDdJqEFFepto"
  },
  {
    "img": "https://c.media-amazon.com/images/I/91OlSrOsY7L._AC_UL320_.jpg",
    "title": "Plaid Boxer Shorts",
    "rating": 4.4,
    "reviews": "(285 reviews)",
    "prevPrice": "$14.99",
    "newPrice": "$8.99",
    "style": "Sleepwear",
    "color": "plaid",
    "category": "shorts",
    "gender": "women",
    "id": "prod_SFA87yjg3WYEYH",
    "price": "price_1RKfnmCkS2P2sDdJJ61E6x3Z"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61gQVDClZRL._AC_SX569_.jpg",
    "title": "Men's Slim Fit Casual Shirt",
    "rating": 4,
    "reviews": "(320 reviews)",
    "prevPrice": "$45.00",
    "newPrice": "$30.00",
    "style": "Comfort",
    "color": "blue",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA8wOTDO03x6Y",
    "price": "price_1RKfnnCkS2P2sDdJFgyNG9E4"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71cLAqOr0tL._AC_SX679_.jpg",
    "title": "Women's High Waist Skinny Jeans",
    "rating": 3,
    "reviews": "(210 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$40.00",
    "style": "Athletic",
    "color": "black",
    "category": "jeans",
    "gender": "women",
    "id": "prod_SFA8ZNDQMU3boM",
    "price": "price_1RKfnnCkS2P2sDdJWvkvc2bj"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71wp-f9m0-L._AC_SY741_.jpg",
    "title": "Unisex Hoodie",
    "rating": 2,
    "reviews": "(500 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$200.00",
    "style": "Professional",
    "color": "gray",
    "category": "hoodies",
    "gender": "unisex",
    "id": "prod_SFA8vNwIQNOXLT",
    "price": "price_1RKfnoCkS2P2sDdJXf3oGgkd"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71BHSXSzqeL._AC_SY741_.jpg",
    "title": "Men's Classic Chinos",
    "rating": 5,
    "reviews": "(190 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$37.00",
    "style": "Other",
    "color": "khaki",
    "category": "pants",
    "gender": "men",
    "id": "prod_SFA8r7Grva7sdM",
    "price": "price_1RKfnoCkS2P2sDdJpJF735vT"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71QXvsxofpL._AC_UL320_.jpg",
    "title": "Women's Summer Dress",
    "rating": 5,
    "reviews": "(275 reviews)",
    "prevPrice": "$70.00",
    "newPrice": "$50.00",
    "style": "Comfort",
    "color": "red",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SFA8cO4QJAJyQn",
    "price": "price_1RKfnpCkS2P2sDdJ88LNLEZC"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81Y6r7df7OL._AC_SX569_.jpg",
    "title": "Men's Business Casual Shirt",
    "rating": 5,
    "reviews": "(275 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$42.00",
    "style": "Professional",
    "color": "white",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA837qzJh8XTi",
    "price": "price_1RKfnpCkS2P2sDdJLryQ8swH"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71htqyXvfSL._AC_SX679_.jpg",
    "title": "Men's Stretch Jeans",
    "rating": 5,
    "reviews": "(315 reviews)",
    "prevPrice": "$80.00",
    "newPrice": "$55.00",
    "style": "Comfort",
    "color": "blue",
    "category": "jeans",
    "gender": "men",
    "id": "prod_SFA8H92uw4Muns",
    "price": "price_1RKfnqCkS2P2sDdJMAbsG0Ok"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71rmcjnJiqL._AC_SX569_.jpg",
    "title": "Casual Hoodie for Women",
    "rating": 5,
    "reviews": "(430 reviews)",
    "prevPrice": "$65.00",
    "newPrice": "$45.00",
    "style": "Athletic",
    "color": "black",
    "category": "hoodies",
    "gender": "women",
    "id": "prod_SFA8HfSjnKNEDm",
    "price": "price_1RKfnrCkS2P2sDdJdV8i8ICf"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61gamoidnBL._AC_SY741_.jpg",
    "title": "Relaxed Fit Cargo Pants",
    "rating": 5,
    "reviews": "(200 reviews)",
    "prevPrice": "$75.00",
    "newPrice": "$50.00",
    "style": "Other",
    "color": "gray",
    "category": "pants",
    "gender": "unisex",
    "id": "prod_SFA84b32mn6nNS",
    "price": "price_1RKfnrCkS2P2sDdJPivioQeq"
  },
  {
    "img": "https://m.media-amazon.com/images/I/51gpWxyUseL._AC_SX679_.jpg",
    "title": "Women's Evening Gown",
    "rating": 5,
    "reviews": "(300 reviews)",
    "prevPrice": "$120.00",
    "newPrice": "$90.00",
    "style": "Professional",
    "color": "navy",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SFA8jS91tmhTV9",
    "price": "price_1RKfnsCkS2P2sDdJBPRLyFAe"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71n4aYYXM-L._AC_SY741_.jpg",
    "title": "Men's Office Pants",
    "rating": 5,
    "reviews": "(270 reviews)",
    "prevPrice": "$90.00",
    "newPrice": "$65.00",
    "style": "Professional",
    "color": "black",
    "category": "pants",
    "gender": "men",
    "id": "prod_SFA8DdNJC2fd3u",
    "price": "price_1RKfnsCkS2P2sDdJ6agAP6KE"
  },
  {
    "img": "https://m.media-amazon.com/images/I/611DCpUuhfL._AC_SL1500_.jpg",
    "title": "Comfy Lounge Hoodie",
    "rating": 5,
    "reviews": "(510 reviews)",
    "prevPrice": "$85.00",
    "newPrice": "$60.00",
    "style": "Comfort",
    "color": "gray",
    "category": "hoodies",
    "gender": "unisex",
    "id": "prod_SFA89kHiXBPlPl",
    "price": "price_1RKfntCkS2P2sDdJJpL9SjmD"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61oW09i5MAL._AC_SX679_.jpg",
    "title": "Casual Summer Dress",
    "rating": 5,
    "reviews": "(340 reviews)",
    "prevPrice": "$55.00",
    "newPrice": "$40.00",
    "style": "Other",
    "color": "yellow",
    "category": "dresses",
    "gender": "women",
    "id": "prod_SFA8BXZEttGMt4",
    "price": "price_1RKfnuCkS2P2sDdJpqfg9fpU"
  },
  {
    "img": "https://m.media-amazon.com/images/I/91tc0Gl1eBL._AC_SX679_.jpg",
    "title": "Men's Flannel Shirt",
    "rating": 5,
    "reviews": "(370 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$45.00",
    "style": "Comfort",
    "color": "red",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA8oFFUQspFZ3",
    "price": "price_1RKfnuCkS2P2sDdJmMVT28fV"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71+riO7d0NL._AC_SX679_.jpg",
    "title": "Skinny Fit Jeans",
    "rating": 5,
    "reviews": "(490 reviews)",
    "prevPrice": "$95.00",
    "newPrice": "$70.00",
    "style": "Athletic",
    "color": "black",
    "category": "jeans",
    "gender": "women",
    "id": "prod_SFA8Pk6H4zc7qv",
    "price": "price_1RKfnvCkS2P2sDdJDZTG4aZJ"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81kAhEYvQwL._AC_UL320_.jpg",
    "title": "Men's Athletic Polo Shirt",
    "rating": 4.5,
    "reviews": "(250 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$35.00",
    "style": "Athletic",
    "color": "green",
    "category": "shirts",
    "gender": "men",
    "id": "prod_SFA8cWB8uPHQHd",
    "price": "price_1RKfnvCkS2P2sDdJDWtGb68K"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81QDD1ULPzL._AC_UL320_.jpg",
    "title": "Women's Maxi Skirt",
    "rating": 4,
    "reviews": "(180 reviews)",
    "prevPrice": "$65.00",
    "newPrice": "$48.00",
    "style": "Comfort",
    "color": "floral",
    "category": "skirts",
    "gender": "women",
    "id": "prod_SFA87Ldt8uSIpF",
    "price": "price_1RKfnwCkS2P2sDdJ3VW0Frk9"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81p-B7OS7VL._AC_UL320_.jpg",
    "title": "Unisex Denim Jacket",
    "rating": 4.8,
    "reviews": "(400 reviews)",
    "prevPrice": "$90.00",
    "newPrice": "$70.00",
    "style": "Other",
    "color": "blue",
    "category": "jackets",
    "gender": "unisex",
    "id": "prod_SFA8XTAw8zqeXl",
    "price": "price_1RKfnwCkS2P2sDdJkUt9JCCW"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71MpFHOznXL._AC_UL320_.jpg",
    "title": "Men's Slim Fit Blazer",
    "rating": 4.7,
    "reviews": "(220 reviews)",
    "prevPrice": "$120.00",
    "newPrice": "$95.00",
    "style": "Professional",
    "color": "navy",
    "category": "blazers",
    "gender": "men",
    "id": "prod_SFA86t2Mv1VPU4",
    "price": "price_1RKfnxCkS2P2sDdJ2fzRhTWh"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61IqZD8hYDL._AC_UL320_.jpg",
    "title": "Women's Athletic Leggings",
    "rating": 4.6,
    "reviews": "(350 reviews)",
    "prevPrice": "$45.00",
    "newPrice": "$32.00",
    "style": "Athletic",
    "color": "black",
    "category": "leggings",
    "gender": "women",
    "id": "prod_SFA80mcwF1KP7V",
    "price": "price_1RKfnyCkS2P2sDdJEIjhoXvT"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71IbGJbFcnL._AC_UL320_.jpg",
    "title": "Men's Crew Neck Sweater",
    "rating": 4.4,
    "reviews": "(290 reviews)",
    "prevPrice": "$70.00",
    "newPrice": "$50.00",
    "style": "Comfort",
    "color": "charcoal",
    "category": "sweaters",
    "gender": "men",
    "id": "prod_SFA8Dt9kfQiC2f",
    "price": "price_1RKfnyCkS2P2sDdJX0AWdrmQ"
  },
  {
    "img": "https://m.media-amazon.com/images/I/815VJpmh7PL._AC_UL320_.jpg",
    "title": "Women's Knit Cardigan",
    "rating": 4.3,
    "reviews": "(260 reviews)",
    "prevPrice": "$60.00",
    "newPrice": "$42.00",
    "style": "Other",
    "color": "beige",
    "category": "cardigans",
    "gender": "women",
    "id": "prod_SFA8YphXAPj13h",
    "price": "price_1RKfnzCkS2P2sDdJP5VYdiEP"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71CFN6Cf9CL._AC_UL320_.jpg",
    "title": "Unisex Graphic T-Shirt",
    "rating": 4.2,
    "reviews": "(450 reviews)",
    "prevPrice": "$35.00",
    "newPrice": "$25.00",
    "style": "Comfort",
    "color": "white",
    "category": "t-shirts",
    "gender": "unisex",
    "id": "prod_SFA8rnBHT2KjCv",
    "price": "price_1RKfnzCkS2P2sDdJgdnkZxJj"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71CxHBIhkiL._AC_UL320_.jpg",
    "title": "Men's Leather Jacket",
    "rating": 4.9,
    "reviews": "(310 reviews)",
    "prevPrice": "$150.00",
    "newPrice": "$120.00",
    "style": "Other",
    "color": "black",
    "category": "jackets",
    "gender": "men",
    "id": "prod_SFA8grrnZqizQy",
    "price": "price_1RKfo0CkS2P2sDdJa945POFX"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71c1emXTEXL._AC_UL320_.jpg",
    "title": "Women's Off-Shoulder Top",
    "rating": 4.1,
    "reviews": "(230 reviews)",
    "prevPrice": "$50.00",
    "newPrice": "$38.00",
    "style": "Athletic",
    "color": "pink",
    "category": "tops",
    "gender": "women",
    "id": "prod_SFA8iNIWOYWe2a",
    "price": "price_1RKfo1CkS2P2sDdJov3TbfIT"
  }
];
export default data;